apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-world.fullname" . }}-nginx-config
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
data:
  default.conf: |
    {{- .Values.nginx.config | nindent 4 }}
