{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sample-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: http
      {{- with .Values.monitoring.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.serviceMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
{{- end }}