apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    {{- if .Values.monitoring.serviceMonitor.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
