apiVersion: v2
name: loki
description: Loki log aggregation for Comind-Ops Platform
type: application
version: 1.0.0
appVersion: "2.9.3"

dependencies:
  - name: loki
    version: "5.41.4"
    repository: https://grafana.github.io/helm-charts


