apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-dev
    app.kubernetes.io/environment: dev
    app.kubernetes.io/part-of: comind-ops-platform
    app.kubernetes.io/component: cache
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: comind-ops-platform
  source:
    repoURL: https://github.com/comind-pro/comind-ops
    targetRevision: main
    path: k8s/charts/platform/redis
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
