apiVersion: v2
name: prometheus
description: Prometheus monitoring stack for Comind-Ops Platform
type: application
version: 1.0.0
appVersion: "2.48.0"

dependencies:
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: https://prometheus-community.github.io/helm-charts


