apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticmq.fullname" . }}-config
  labels:
    {{- include "elasticmq.labels" . | nindent 4 }}
data:
  elasticmq.conf: |
    {{- .Values.elasticmq.config | nindent 4 }}
