apiVersion: v2
name: elasticmq
description: A Helm chart for ElasticMQ SQS-compatible message queue
type: application
version: 0.1.0
appVersion: "1.5.7"
keywords:
    - elasticmq
    - sqs
    - message-queue
    - aws-compatible
home: https://github.com/softwaremill/elasticmq
sources:
    - https://github.com/softwaremill/elasticmq
maintainers:
    - name: Platform Team
      email: platform@comind-ops.local
