apiVersion: v2
name: promtail
description: Promtail log collector for Loki
type: application
version: 1.0.0
appVersion: "2.9.3"

dependencies:
  - name: promtail
    version: "6.15.3"
    repository: https://grafana.github.io/helm-charts


